import type { CritiqueStandardId } from "@/lib/critiqueStandards";

function section(title: string, body: string) {
  return `\n\n## ${title}\n${body}\n`;
}

function suggestionsToBullets(suggestions: string[]) {
  return suggestions.map((s) => `- ${s}`).join("\n");
}

export function generateImprovedPolicyMVP(params: {
  originalTitle: string;
  originalText: string;
  selectedStandards: CritiqueStandardId[];
  perStandard: { standardId: CritiqueStandardId; score: number; suggestions: string[] }[];
  overallScore: number;
}) {
  const { originalTitle, originalText, perStandard, overallScore } = params;

  // Base: keep original text but add a structured “enhanced” layer
  const header = `# ${originalTitle} (Dynovare AI Generated)\n\n` +
    `**Generated by Dynovare Policy Intelligence Platform**\n` +
    `**Basis:** Critique score ${overallScore}/100 + standards-driven improvements\n`;

  const improvements = perStandard
    .sort((a, b) => a.score - b.score)
    .map((r) => {
      return section(
        `Improvements for ${r.standardId.replaceAll("_", " ").toUpperCase()}`,
        suggestionsToBullets(r.suggestions)
      );
    })
    .join("");

  const structureAdditions =
    section(
      "Policy Objectives",
      "- Improve energy access, reliability, and affordability.\n- Increase renewable integration and grid resilience.\n- Strengthen governance, accountability, and performance monitoring."
    ) +
    section(
      "Implementation Roadmap",
      "- Phase 1 (0–2 years): institutional setup, baseline data, quick wins.\n- Phase 2 (3–5 years): scale programs, financing mechanisms, enforcement.\n- Phase 3 (5+ years): sustained investments, periodic reforms, impact evaluation."
    ) +
    section(
      "Monitoring & Evaluation",
      "- KPIs: access rate, reliability indices, tariff affordability, emissions intensity.\n- Baselines: establish within first 6 months.\n- Reporting: quarterly progress + annual review.\n- Evaluation: independent assessment every 2 years."
    ) +
    section(
      "Risk Register & Mitigation",
      "- Funding risk → diversified financing + phased delivery.\n- Governance risk → audits + transparency + clear accountability.\n- Capacity risk → training + partnerships + technical assistance."
    );

  const finalText =
    header +
    section("Executive Summary", "This improved policy version strengthens alignment to selected standards, adds governance and M&E structure, and clarifies implementation pathways.") +
    section("Original Policy (Reference)", originalText.trim()) +
    section("Enhanced Additions", "The sections below are added to strengthen the policy against the selected critique standards.") +
    improvements +
    section("Recommended Structure (Consolidated)", "You can consolidate these additions into a single coherent policy document using the structure below.") +
    structureAdditions;

  return finalText;
}
